### ISSUE TITLE
app appears to hang when credentials have expired

### ISSUE THREAD

**Issue by judell** [turbot/steampipe#1103]
I have one AWS SSO connection that needs frequent renewal. When it's expired, Steampipe hangs until I fix it.

**Comment by kaidaguerre** [comment]
I'm seeing the same for bad credentials on a normal aws account as well - looking

**Comment by kaidaguerre** [comment]
aws plugin bug, fixed by https://github.com/turbot/steampipe-plugin-aws/commit/35a71b81c07408bdf8d6de65241d107533535ad3

@judell please could you verify this n o longer happens when using the latest AWS plugin

**Comment by judell** [comment]
Sorry for delay, but I just noticed that this still happens. The plugin log says:

[ERROR] steampipe-plugin-aws.plugin: [ERROR] streamRows error chan select: ExpiredToken: The security token included in the request is expired

But the app just spins. It would be good to surface that message to the user. Also helpful would be to tell the user that if steampipe is running as a service, it will have to be restarted to recognize the new creds.

**Comment by judell** [comment]
Hmm. Not sure how that happened, seems OK now, reclosing issue.

> select * from aws_all.aws_account

Error: 1 connection failed:
connection 'aws_turbot_sso': rpc error: code = Unknown desc = InvalidClientTokenId: The security token included in the request is invalid
        status code: 403, request id: 129cdf6d-a684-4f79-96a8-5a474bd5cb97 (SQLSTATE HV000)

**Comment by judell** [comment]
And ... reopening again, @kai. A user reports:

> Currently, if any token is expired, it sits for a long time before failing.  Is this something that can be fixed eventually?  Or maybe a flag that would skip expired tokens but report?

I will recheck this myself once my current AWS SSO creds expire again.

**Comment by psolomon-opploans** [comment]
As I'm pushing for adoption of this great tool at our company, this issue is probably the biggest for us.  If users can immediately know their tokens are expired, that will greatly help with devs acceptance this tool.  At the very least, maybe add a "check" feature to check tokens for whatever plugin you are using.

**Comment by rajlearner17** [comment]
@psolomon-opploans @judell   it's wired I tried to replicate the same with the following versions
steampipe version `0.11.0`
AWS plugin - `0.43.0` 
With my SSO token expired for the below connection, I get the error instantly

Can you pls check your current versions and share them here?

```
select * from aws_sso.aws_s3_bucket
Error: SSOProviderInvalidToken: the SSO session has expired or is invalid (SQLSTATE HV000)
>
```
There could be something which we need to re-produce

We have a fix contributed [here](https://github.com/turbot/steampipe-plugin-aws/pull/839), which requires further testing/reviews in progress.

**Comment by kaidaguerre** [comment]
@judell let me know if you can reproduce. Is this looking like a plugin issue rather than a Steampipe issue?

**Comment by psolomon-opploans** [comment]
I still get the hang after I updated to those versions.  Is there something in my AWS config I need to turn on or off to get this to work?

**Comment by judell** [comment]
reposting from Steampipe Slack:

I am able to repro the problem on my machine. 

I have a `~/.aws/config` like so:

```
[profile SSO-ReadOnly-6054...
sso_start_url = https://d-9a6...
sso_region = us-east-2
sso_account_id = 6054...
sso_role_name = SSO-ReadOnly
aws_access_key_id="ASIAY...
aws_secret_access_key="iLvv...
aws_session_token="IQoJb3JpZ2l..

Steampipe hangs because I believe that it's expired. When I swap in fresh creds, it doesn't hang. 

I don't, however, see a difference between the two cases when I do this:

```
aws --profile SSO-ReadOnly-6054... --region us-east-2 sts get-caller-identity
```

The response in both cases:

> The SSO session associated with this profile has expired or is otherwise invalid. To refresh this SSO session run aws sso login with the corresponding profile.

However I do find this in the database (not plugin) log:

> 2021-12-22T11:04:32.710-0800 [WARN]  hub: stream receive error rpc error: code = Unknown desc = ExpiredToken: The security token included in the request is expired

Surfacing that message would be super-helpful.

**Comment by dbmurphy** [comment]
> We have a fix contributed [here](https://github.com/turbot/steampipe-plugin-aws/pull/839), which requires further testing/reviews in progress.

This is now [plugin-aws#847](https://github.com/turbot/steampipe-plugin-aws/pull/847)

**Comment by judell** [comment]
Thanks @dbmurphy!

I tried both the stock plugin and your branch just now, with expired creds, and got this in both cases:

```
> select * from aws_turbot_sso.aws_account
Error: InvalidClientTokenId: The security token included in the request is invalid
        status code: 403, request id: bf386d24-c89a-4880-8db2-16a0c72942bb (SQLSTATE HV000)
```

It's good that this is reported, though I'm puzzled since I didn't see this last time I checked, and don't see any recent commits related to this, 

I also didn't see a reauth attempt on the dbmurphy branch, which may have to do with my setup: running Steampipe in WSL2 where there is no browser to be launched.

**Comment by judell** [comment]
Closed in favor of https://github.com/turbot/steampipe-plugin-aws/issues/849
